### ISSUE TITLE
Do you have a link where I can buy the product this driver is tested on?

### ISSUE THREAD

**Issue by magnublo** [ciembor/gm1356-linux-driver#7]
Great work on this driver!

I have a problem similar to that of @HaasNL2 in the [other issue](https://github.com/dobra-noc/gm1356/issues/3). A big industrial plant is being built next to my home, and I need to document the noise. I plan on mounting the decibel meter outside my house, wire it to a Raspberry Pi, periodically push the data to GitHub, and use GitHub Actions and Twitter API to automatically make a tweet every time the noise exceeds the law, and tag relevant politicians in the tweet. I plan to run it 24/7. If you immediately see a technical reason that this will not work out, it would be great if you let me know ;)

Do you know where I can buy a device which this driver is known to work on? The README.md specifies serial number HA:1303162, but I can't find a product listing when I google it...

**Comment by davegudge** [comment]
Here's the cover of the manual for the hardware I purchased: 

![IMG_2760](https://user-images.githubusercontent.com/1736807/95722603-0f710b00-0c6c-11eb-921b-1c3a14b3ef35.JPG)


[amazon link](https://www.amazon.co.uk/Handheld-Measurement-Analysis-Industry-Included/dp/B01M32WX3H/ref=asc_df_B01M32WX3H/)

**Comment by magnublo** [comment]
Thanks a lot! It's in the mail now.

**Comment by davegudge** [comment]
> periodically push the data to GitHub, and use GitHub Actions and Twitter API to automatically make a tweet every time the noise exceeds the law, and tag relevant politicians in the tweet. I plan to run it 24/7. If you immediately see a technical reason that this will not work out, it would be great if you let me know ;)

I'm not sure how much flexibility GitHub Actions will give you. You may be better off 'working' with the data on the Raspberry Pi, and then posting to Twitter (from the Raspberry Pi).

You will probably find that you'll need to sample the data to detemine a breach of a given threshold, for example, if you look at the output below (raw data vs 5 second sample vs a 10 second sample):

![sample](https://user-images.githubusercontent.com/1736807/96989503-ac119380-151d-11eb-836f-7805f96a68c2.png)

If I defined by breach threshold as 65db(A), a lot of tweets would have been sent when using the raw data (the narrow peaks are cars passing). The red line (5 second average) and the blue line (10 second average) give you a better idea of an ongoing loud noise.
